# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

# RUN ln -s /usr/local/bin/site-packages/python3/swatooth_rest_api /usr/local/bin/site-packages/python3.7/swatooth_rest_api

# WORKDIR /project/sawtooth-marketplace

# ENV PATH $PATH:/project/sawtooth-marketplace/bin

# EXPOSE 8000/tcp

# CMD ["marketplace-rest-api"]